name: Send Code to Website

on:
  release:
    types: [created]

jobs:
  update_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy files
        run: |
          rm -rf ../JaxGM.github.io/notationSheet/*
          mkdir -p ../JaxGM.github.io/notationSheet/
          cp -r ./!(.github|LICENSE|README.md) ../JaxGM.github.io/notationSheet/
      - name: Commit changes
        run: |
          cd ../JaxGM.github.io/
          git config --global user.name "JaxGM"
          git config --global user.email "flume_prowl_0n@icloud.com"
          git add .
          git commit -m "Send code to website"
          git push origin main
