name: Update notation sheet v12

on:
  release:
    types:
      - created
    tags:
      - Published
  push:
    branches:
      - main

jobs:
  update_notation_sheet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone JaxGM/JaxGM.github.io
      uses: actions/checkout@v2
      with:
        repository: JaxGM/JaxGM.github.io
        path: jaxgm.github.io

    - name: Delete contents of notationSheet folder
      run: rm -rf jaxgm.github.io/notationSheet/*

    - name: Copy new release contents to notationSheet folder
      run: mv chessNotationSheet/* jaxgm.github.io/notationSheet/

    - name: Commit and push changes
      run: |
        cd jaxgm.github.io
        git config --local user.email "flume_prowl_0n@icloud.com"
        git config --local user.name "JaxGM"
        git add notationSheet
        git commit -m "Update notation sheet"
        git push
