name: Update Github Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: JaxGM.github.io
        email: flume_prowl_0n@icloud.com
        name: JaxGM
        commit_message: Update notationSheet folder
