name: Update Notation Sheet

on:
  push:
    branches:
      - main

jobs:
  update_notation_sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Debug
      run: |
        pwd
        ls JaxGM
        ls JaxGM/chessNotationSheet

    - name: Clear Notation Sheet Folder
      run: rm -rf notationSheet/*

    - name: Copy Chess Notation Sheet
      run: cp -R JaxGM/chessNotationSheet/. notationSheet/

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Update notation sheet'
        add: 'notationSheet'
