name: Update Notation Sheet

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2.5.2
      with:
        node-version: '16.x'
#     - name: Deploy to GitHub Pages
#       uses: JamesIves/github-pages-deploy-action@v4.4.1
#       with:
#         token: ${{ secrets.ACCESS_TOKEN }}
#         branch: main
#         folder: notationSheet
#         workspace: chessNotationSheet
#         target-folder: ''
#         git-config-name: 'JaxGM'
#         git-config-email: 'flume_prowl_0n@icloud.com'
#         commit-message: "Deployed release ${{ github.event.release.tag_name }}"
    - name: Set git user
      run: |
        git config --global user.name "JaxGM"
        git config --global user.email "flume_prowl_0n@icloud.com"
