name: Update Notation Sheet

on:
  push:
    branches:
      - main

jobs:
  update_notation_sheet:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout JaxGM/JaxGM.github.io repo
        uses: actions/checkout@v2
        with:
          repository: JaxGM/JaxGM.github.io
          ref: main
      - name: Remove contents of notationSheet folder
        run: rm -rf notationSheet/*
      - name: Checkout JaxGM/chessNotationSheet repo
        uses: actions/checkout@v2
        with:
          repository: JaxGM/chessNotationSheet
          ref: main
#       - name: Copy contents of chessNotationSheet into notationSheet folder
#         run: cp -R JaxGM/chessNotationSheet/* notationSheet/
      - uses: actions/checkout@v2
      - name: creates output
        run:  sh ./build.sh # some command from your repository that creates
                            # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io.'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
