name: Update Notation Sheet

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: JaxGM/chessNotationSheet
        ref: ${{ github.event.release.tag_name }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        folder: notationSheet
        repository: JaxGM/JaxGM.github.io
        cname: jaxgm.github.io
        commit_message: "Deployed release ${{ github.event.release.tag_name }}"
    - name: Set git user
      run: |
        git config --global user.name "JaxGM"
        git config --global user.email "flume_prowl_0n@icloud.com"
