name: Update Notation Sheet

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
#       - name: creates output
#         run:  sh ./build.sh
#       - name: Install mustache (to update the date)
#         run:  apk add ruby && gem install mustache
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/main'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./files/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./notationSheet/
      - name: Pushes to another repository - dev
        id: push_directory_dev
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/dev'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./files/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./notationSheet/dev/
